name: Go Build on Tag

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Verify tag is on main
        run: |
          git fetch origin main
          git merge-base --is-ancestor ${{ github.sha }} origin/main || \
            (echo "Tag is not on main branch" && exit 1)

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Install dependencies
        run: go mod download

      - name: Release
        run: make release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ./dist/th*
          draft: false
          prerelease: false
          generate_release_notes: true
